pages/knowledgebases/index.vue
prisma/migrations/20240305202320_knowlegebase_files/migration.sql
prisma/migrations/20240305205052_files_cascade_deletion/migration.sql
prisma/schema.prisma
server/api/knowledgebases/index.get.ts
server/api/knowledgebases/index.post.ts
vercel.json

1. Prisma schema update
2. API update
3. Front-end update

multi-files knowledgebase support

---

components/Chat.vue
server/api/knowledgebases/index.post.ts

- 如果不存在tmp文件夹则自动创建，避免上传 knowledge 报错
- 对话内容框适配暗主题

修复tmp文件夹不存在会报错

---

components/Chat.vue
components/ModelsDropdown.vue
pages/settings/index.vue
server/api/models/chat/index.post.ts
server/api/models/index.get.ts
server/middleware/keys.ts
server/utils/models.ts
utils/settings.ts

Added OpenAI models support in knowledge based chat.
This PR is to address #13 .
The same support in the general chat will be added in a separate PR.

feature: openai models support in knowledgebase chat

---

components/Chat.vue
components/ModelsDropdown.vue
nuxt.config.ts
package.json
pnpm-lock.yaml

- 首次加载页面时默认将模型列表中的第一个模型设置为当前的聊天模型
- 保存知识库所选的模型到本地存储中
- 重构 ModelsDropdown 组件，调整聊天页面局部布局

新增自动设置和存储当前模型

---

components/Chat.vue
pages/instructions/index.vue
prisma/migrations/20240309101210_instruction/migration.sql
prisma/schema.prisma
server/api/instruction/[id].delete.ts
server/api/instruction/[id].put.ts
server/api/instruction/index.get.ts
server/api/instruction/index.post.ts
utils/settings.ts

feat: instruction 数据迁移至 sqlite

---

package.json
pnpm-lock.yaml
server/api/models/chat/index.post.ts
server/api/models/index.get.ts
server/utils/models.ts

Anthropic API support in knowledge based chat

Anthropic API support in knowledge based chat

---

docker-compose-ollama.yaml
package.json
pnpm-lock.yaml
server/api/chat/index.ts
server/api/instruction/[id].delete.ts
server/api/instruction/[id].put.ts
server/api/instruction/index.get.ts
server/api/instruction/index.post.ts
server/api/knowledgebases/[id].delete.ts
server/api/knowledgebases/[id].get.ts
server/api/knowledgebases/index.get.ts
server/api/knowledgebases/index.post.ts
server/api/models/chat/index.post.ts
server/api/models/index.get.ts
server/middleware/ollama.ts
server/utils/models.ts
server/utils/prisma.ts

https://github.com/sugarforever/chat-ollama/issues/55
ChatOllama支持如下OpenAI文本嵌入模型
```
export const OPENAI_EMBEDDING_MODELS = [
"text-embedding-3-large",
"text-embedding-3-small",
"text-embedding-ada-002"
];
```

feat: support openai embedding models

---

components/Chat.vue
components/Download.vue
components/KnowledgeBaseChat.vue
components/Models.vue
components/ModelsDropdown.vue
pages/knowledgebases/index.vue
pages/settings/index.vue
server/api/chat/index.ts
utils/settings.ts

- 修复在服务端渲染时提示 localStorage 未定义的问题
- 使用 useStorage 重构本地数据的存储
https://github.com/sugarforever/chat-ollama/issues/45#issuecomment-1993686377

fix: Fix the issue of localStorage not existing when SSR #45

---

pages/knowledgebases/index.vue
server/api/knowledgebases/index.post.ts

以下是本次修正的內容
- 上傳知識庫時，確保至少上傳一個檔案
- 上傳知識庫時，確保 Emdedding Model 存在於 Ollama 伺服器
- 上傳知識庫發生錯誤時，將按鈕恢復成非 Loading 狀態
- 上傳知識庫發生錯誤時，將已建立的 Knowledge Base 資料刪除，避免遺留在資料庫

Improve UX when creating knowledge bases

---

pages/settings/index.vue
server/middleware/keys.ts
server/utils/models.ts
utils/settings.ts

- openai 和 anthropic 支持自定义域名 #66
- 重构设置页面
@sugarforever 需要你帮忙看下图中框选部分的代码是否正确

feat: support openai and anthropic's url  #66

---

pages/knowledgebases/index.vue
server/api/knowledgebases/index.post.ts

feat: check if the knowledge base already exists and prompt

---

components/Download.vue
server/api/models/pull/index.post.ts

本次新增 & 調整內容如下
---
- 下載模型增加必填進行防呆
- 下載模型失敗或不存在的模型時提供錯誤訊息
- 增加 ollama model library 超連結

Improve UX when download models

---

server/utils/models.ts

Issue https://github.com/sugarforever/chat-ollama/issues/74

feat: support Claude 3 Haiku

---

components/Chat.vue
package.json
pnpm-lock.yaml

feat: code block coloring style

---

components/ModelsDropdown.vue
package.json
pages/settings/index.vue
pnpm-lock.yaml
server/api/models/index.get.ts
server/middleware/keys.ts
server/utils/models.ts
utils/settings.ts

feat: Azure OpenAI support

---

app.config.ts
components/Chat.vue
components/ChatInputBox.vue
components/TheTextarea.vue
nuxt.config.ts
package.json
pnpm-lock.yaml

- 发送消息支持 **Enter** 和 **Shift + Enter** 两种方式
- 限制输入框最大行数
- 新的UI
与 #98 PR 改动相似，已和 @gslin1224 沟通😄

feat: new UX for chat box

---

components/Chat.vue
components/ChatInputBox.vue
layouts/default.vue
pages/chat/index.vue
pages/knowledgebases/[id].vue
pages/settings/index.vue

- 移除聊天界面有两个滚动条的显示
- 聊天输入框没有粘在页面底部 #101
- 聊天内容样式的调整

fix: ui improvement

---

components/Chat.vue
layouts/default.vue

fix: fix chat list cannot scroll to the bottom

---

pages/settings/index.vue
server/api/models/index.get.ts
server/middleware/keys.ts
server/utils/models.ts
utils/settings.ts

1. Add moonshot service provider.
2. There are three models as follows:
moonshot-v1-8k
moonshot-v1-32k
moonshot-v1-128k
3. Reuse openai's sdk
4. Pass-test

add moonshot service provider

---

components/TheTextarea.vue

fix: fix the enter key when using the IME

---

pages/knowledgebases/index.vue

improve: new UX for the table

---

app.vue
assets/index.scss
components/Chat.vue
layouts/default.vue

improve: improve chat UI  #123

---

pages/knowledgebases/index.vue

minor tweaks

---

assets/index.scss
nuxt.config.ts
package.json
pnpm-lock.yaml

bugfix: google fonts

---

components/Chat.vue

聊天响应数据有可能没有 content 字段，所以通过判断是否有响应回复内容来处理  loading 移出时机

improve: improve loading display

---

components/Chat.vue
server/api/models/chat/index.post.ts

bugfix: issue 160

---

server/api/knowledgebases/index.post.ts
server/api/models/index.delete.ts
server/api/models/index.get.ts
server/api/models/pull/index.post.ts
server/utils/index.ts
server/utils/ollama.ts

看到很多人反馈下面的问题
于是尝试将上面的错误改成下面的这种错误提示

check if the Ollama service is available and provide possible error resolution methods

---

components/Chat.vue
components/ModelsDropdown.vue
server/api/models/chat/index.post.ts
server/api/models/index.get.ts
server/utils/models.ts

#161 
利用model, family的组合来标识模型，确保唯一性。

extend model identification to model + family

---

server/api/models/chat/index.post.ts

Issue #131 
Include chat history in the prompt of the chat completion request. LLM will learn the chat history now.
Current implementation will rely on the client side to pass on the chat history.

feat: include chat history in chat completion

---

components/Chat.vue
components/ModelsDropdown.vue
package.json
pages/settings/index.vue
pnpm-lock.yaml
server/api/models/index.get.ts
server/middleware/keys.ts
server/utils/models.ts
utils/settings.ts

feat: support Groq API

---

.env.example
README.md
package.json
pnpm-lock.yaml
server/retriever/index.ts
server/utils/vectorstores.ts

Added Milvus vector database support with 2 additional environmental variables:
```
VECTOR_STORE=milvus
CHROMADB_URL=http://localhost:8000
MILVUS_URL=http://localhost:19530
```

feat: support milvus vector database

---

server/api/knowledgebases/index.post.ts

Adding multiple docs to Milvus in multiple `addDocuments` calls will fail.

bugfix: adding multi docs to milvus

---

pages/settings/index.vue

@sugarforever 
- 重构了代码，现在理论上新增一种模型配置会更简单
- 重构了 UI 的交互

[Settings Page] refactor code and new UX

---

server/api/knowledgebases/[id].put.ts

revert: revert file

---

pages/settings/index.vue

fix: improve UI #208

---

pages/knowledgebases/index.vue

fix: cannot create new knowledge if no url were provided

---

.vscode/settings.json
components/Chat.vue
components/ChatSettings.vue
pages/settings/index.vue
prisma/schema.prisma
server/middleware/keys.ts
server/utils/models.ts
utils/settings.ts

模型增加家族名、groq 支持自定义 host

---

components/KnowledgeBaseDeletePrompt.vue
pages/knowledgebases/index.vue

#228 
Users need to confirm before deleting knowledge bases, so that it can avoid deletion by mistake.

confirm before deleting knowledge base

---

components/Chat.vue
components/ChatMessageActionMore.vue
components/ChatSessionList.vue
pages/chat/index.vue

- 支持消息的 复制、重发、删除
- 修复代码块行内容过长会导致页面出现横向滚动条（现在代码块内有横向滚动条了）

Suport copy, resend, and delete message

---

docker-compose.yaml
docker-compose_gpu.yaml

Add Redis to docker compose services so that parent document retriever becomes the default retrieval strategy.

feat: added Redis to docker compose services

---

components/Chat.vue
components/Sources.vue
server/api/models/chat/index.post.ts
server/retriever/index.ts
server/utils/rag.ts

Display the source documents that's used as context in the LLM inference.

feat: reference documents

---

components/ChatMessageActionMore.vue

fix: remove the permission check

---

.vscode/settings.json
components/Chat.vue
components/Sources.vue
composables/clientDB.ts
server/api/models/chat/index.post.ts

- 将关联知识库信息一起存储到本地数据库中
- 修复 ts 类型报错
- 关联知识库展示适配暗模式

存储消息的关联知识库信息

---

package.json
pnpm-lock.yaml
server/utils/rag.ts

bugfix: replaced puppeteer with cheerio for simpler deployment

---

.vscode/settings.json
components/FileButton.vue
components/FileSelector.vue
components/KnowledgeBaseForm.vue

feat: add folder upload support to knowledge base #140 #76 #254

---

components/ChatSettings.vue
components/ModelsSelectMenu.vue

fix: avoid warnings when build

---

assets/index.scss

inherit font family in messages

---

components/ChatSettings.vue
components/ModelsSelectMenu.vue
components/settings/SettingsChatSettings.vue
composables/chat.ts
composables/store.ts

fix: fixed duplicate values appearing

---

components/FileSelector.vue
package.json
pnpm-lock.yaml
server/utils/rag.ts

添加了 csv 支持，直接使用langchain 自带的loader ，xls 可以以后考虑 ，毕竟格式可以互转

Add csv support

---

server/api/models/index.get.ts
server/middleware/keys.ts
server/middleware/ollama.ts
server/utils/models.ts
utils/settings.ts

NGINX 默认会忽略下划线的 header 字段 #205

fix: replace underscores with hyphens to compatible with NGINX #205

---

components/Chat.vue

feat: support user-defined scrolling while chatting

---

components/KnowledgeBaseForm.vue
pages/knowledgebases/index.vue
server/api/knowledgebases/[id].delete.ts
server/api/knowledgebases/[id].put.ts
server/api/knowledgebases/index.post.ts
server/types/index.ts
server/utils/http.ts
server/utils/knowledgeBase.ts

#348 
知识库可以设置可见性。公开可见的知识库所有用户都可以使用。

feat: knowledge base visibility and access control

---

components/ChatSessionList.vue

fix: "session-item" hover style problem

---

components/Chat.vue
pages/chat/index.vue

- 修复切换会话后会把上一个会话的内容带过来的问题 #381
- 修复对话回复速度慢的问题（尤其是 groq 的模型特别明显）

fix: the chat session still outputs messages when it is aborted or changed

---

README.md

docs: simplified doc

---

server/api/knowledgebases/[id].put.ts
server/api/knowledgebases/index.post.ts
server/utils/models.ts

优先判断 api 的文本嵌入模型，再去判断 ollama 的本地嵌入问本模型

improve: optimizing embedding model detection logic

---

server/middleware/auth.ts

change error output to log

---

components/ChatSessionList.vue

fix: 修复标题栏按钮不展示bug

---

server/api/models/chat/index.post.ts

#432 
The field `stream: false` in request is not honored in model chat when the knowledgeId is not set.
```
{
"model": "gpt-3.5-turbo",
"family": "OpenAI",
"messages": [
{
"role": "user",
"content": "What's the score of the game between Leverkusen and Roma last night?"
}
],
"stream": false
}
```

bugfix: stream false not honored by model chat

---

components/MobileMenu.vue
composables/useMenus.ts
layouts/default.vue

https://github.com/sugarforever/chat-ollama/assets/5283258/dfb5af86-4f95-4ab2-8bc0-f54424f66b72

顶部导航栏支持响应式

---

config/models.ts
package.json
pnpm-lock.yaml
server/models/genai/generative-ai.ts
server/models/genai/utils.ts
server/utils/models.ts

Support Google newly released model variant `gemini-1.5-flash-latest`

feat: support Gemini 1.5 Flash

---

components/ChatSessionList.vue
locales/en-US.json
locales/zh-CN.json

fix: Fixed DeleteChat useDialog prompt issue

---

components/Sources.vue

fix: fixed incomplete content display  #486

---

components/KnowledgeBaseForm.vue
composables/useModels.ts

简单的区分文本嵌入模型

---

components/ChatMessageItem.vue
composables/useModels.ts
composables/worker-chatRequest.ts

修复模型名含有 / 时不能正确提取模型名

---

components/Sources.vue

知识库来源改成点击显示详情

---

components/settings/SettingsServers.vue
server/middleware/keys.ts
server/models/genai/generative-ai.ts
server/utils/models.ts
utils/settings.ts

gemini 支持使用代理

---

components/ChatSessionList.vue

会话列表增强当前会话高亮识别度

---

server/utils/models.ts

fix: Fix incorrect handling of OpenAI's default endpoint

---

components/ChatMessageItem.vue

TO SOLVE [issue-554](https://github.com/sugarforever/chat-ollama/issues/554)

fix: chatmessage question html-like tags incorrect display

---

config/models.ts

https://console.groq.com/docs/models

feat: groq llama-3.1 and gemma2

---

components/settings/LanguageSelectMenu.vue
composables/useMenus.ts
locales/en-US.json
locales/zh-CN.json
middleware/defaultPage.global.ts
pages/welcome.vue

feat: support custom the default page

---

config/models.ts
package.json
pnpm-lock.yaml
server/api/models/chat/index.post.ts
server/models/genai/generative-ai.ts
server/models/genai/output_parsers.ts
server/models/genai/types.ts
server/models/genai/utils/common.ts
server/models/genai/utils/tools.ts
server/models/genai/utils/zod_to_genai_parameters.ts
server/utils/mcp.ts

The tool binding with Gemini models is not implemented yet.
The blocker is that, the current MCP server tools schema may not be compatible with Gemini function tools.

feat: support with gemini 2.0 flash

---

package.json
pnpm-lock.yaml

Run `npx update-browserslist-db@latest`

feat: update-browserslist-db

---

composables/useOpenAIModels.ts

Use Nuxt's built-in composables for i18n instead

fix: pnpm run build failure

---

components/Chat.vue
components/ChatMessageItem.vue
components/MarkdownPreview.vue

The AI message is previewable.

feat: Markdown content preview

---

Dockerfile
package.json
pnpm-lock.yaml
server/api/auth/login.post.ts

Looks `bcrypt` is causing issue in running ChatOllama docker image. Replaced it with `bcrypt.js`.

feat: replace bcrypt with bcrypt.js

---

.env.example
components/Chat.vue
components/ChatSettings.vue
composables/useMenus.ts
nuxt.config.ts
pages/instructions/index.vue
server/api/instruction/[id].delete.ts
server/api/instruction/[id].put.ts
server/api/instruction/index.get.ts
server/api/instruction/index.post.ts

Implement comprehensive feature flags for Knowledge Base, Realtime Chat, Models Management, and Instructions
- Add server-side environment variables for all features:
* KNOWLEDGE_BASE_ENABLED (default: true)
* REALTIME_CHAT_ENABLED (default: true)
* MODELS_MANAGEMENT_ENABLED (default: true)
* INSTRUCTIONS_ENABLED (default: true)
- Implement SSR-friendly feature flags using Nuxt runtime config
- Add server utilities for centralized feature checks
- Protect all feature-specific API endpoints with 403 responses when disabled
Knowledge Base:
- Complete API protection (all endpoints)
- Route middleware with redirect to /welcome
- Conditional UI hiding in chat components
- Menu item conditionally shown
Realtime Chat:
- Audio session API protection
- Route middleware with redirect to /welcome
- …

Implement comprehensive feature flags

---

.env.example
server/api/auth/google/callback.get.ts
server/api/auth/google/login.get.ts

It's not needed to expose it to public. Rename it to APP_BASE_URL

NUXT_PUBLIC_BASE_URL is public visible
