components/Chat.vue, package.json, pages/knowledgebases/index.vue, pnpm-lock.yaml, server/api/knowledgebases/index.post.ts
感觉我对这个项目有点上头了，又搞了点事情😂
- Chat 页面添加容错处理
- 支持 .txt,.json,.md,.doc,.docx,.pdf 格式文件的上传
- 重构文件的内容的读取，直接将文件的 Buffer 转 Blob，不需要再将文件存储本地
=> 支持更多类型的文件上传

server/middleware/ollama.ts
- 移除 url 末尾的斜杠，避免前端输入的 url 中末尾多一个斜杠导致无法访问 ollama
=> fix: remove the trailing slash in the URL

server/middleware/ollama.ts
如果 localhost 不能成功指向到 127.0.0.1 就会报下面的错误，所以默认直接用 127.0.0.1，关联问题 #52 
```
[nuxt] [request error] [unhandled] [500] fetch failed
at Object.fetch (node:internal/deps/undici/undici:11372:11)  
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
=> fix: replace localhost with 127.0.0.1

pages/knowledgebases/index.vue
Use list to display no more than 8 files in knowledge base. When there are more than 8, display the rest with 3 dots.
=> changed knowledgebase files list display

assets/index.scss, components/Chat.vue, components/ChatInputBox.vue, package.json, pnpm-lock.yaml, types/markdown-it.d.ts, utils/settings.ts
- Chat.vue 文件使用 ts 重构，并且样式做了轻微调整
-  #118
@sugarforever 前端已经实现了取消请求功能
现在发现的问题是在前端取消请求后再发消息需要等待很久，感觉是要等上个内容生成结束才会继续下一个，所以我感觉后端也需要取消 Ollama 的输出，但我没有找到相关的 API，需要你帮忙看看。
=> 支持手动停止内容输出功能

components/Chat.vue, server/api/models/chat/index.post.ts
In the front end, `loading` type message is used to render the loading status while waiting for server response.
But such type of message  along with other messages got sent as chat history. It broke the chat feature at the server side.
In this PR, the loading type message is filtered out to make sure the user's query is always the latest one in the chat history.
=> assistant loading type message got sent along with other messages

package.json, pages/settings/index.vue, pnpm-lock.yaml, server/api/models/index.get.ts, server/middleware/keys.ts, server/utils/models.ts, utils/settings.ts
Support Google Gemini models. It includes generative chat and embedding models.
Chat models:
- gemini-1.0-pro
- gemini-1.0-pro-vision-latest
Embedding model:
- embedding-001
The gemini 1.5 pro model is still under preview which is not available via generative API yet. It will be supported once it's public accessible via API.
=> feat: support Gemini models

components/KnowledgeBaseUpdateForm.vue
The problem is not completely resolved. When a new knowledge base has a URL, or when knowledge is modified (even if there is no URL), there are still the same errors, but adding or modifying the PDF to the knowledge base is successful.
_Originally posted by @Rock1965 in https://github.com/sugarforever/chat-ollama/issues/221#issuecomment-2041456584_
=> fix: failed to update knowledgebases when urls is empty

.env.example, components/Sources.vue, package.json, pnpm-lock.yaml, server/api/models/chat/index.post.ts, server/retriever/index.ts
To minimize the effort in running RAG with reranker, this PR is to allow users to use Cohere Rerank API to improve the RAG quality.
How to use:
- By adding environmental variable `COHERE_API_KEY`, retrieved documents will be reranked before passing on to LLM.
=> feat: cohere ranker

nuxt.config.ts
ChatOllama needs a type of APIs documentation so that developers can use the endpoints as needed.
Nitro, the underlying infra of Nuxt has the experimental feature to support OpenAPI compatible API doc:
https://nitro.unjs.io/config#experimental
Notice that, the current doc `http://localhost:3000/_nitro/openapi.json` has not enough API schema information, for example the payload schema of `/v1/models/chat`.
It will be improved in the future. Let's use this PR to expose the base API documentation for now.
=> feat: nitro powered openapi endpoint

components/KnowledgeBaseForm.vue, pages/knowledgebases/index.vue
重构文本嵌入模型输入框的操作交互，其中 Ollama 的文本嵌入模型来自于知识库列表中的 embedding 字段
关联 #286
=> refactor: refactor embedding input UX

components/KnowledgeBaseForm.vue, composables/utils.ts, package.json, pnpm-lock.yaml, server/api/knowledgebases/index.post.ts, server/types/index.ts, server/utils/http.ts, server/utils/rag.ts, server/utils/recursiveUrlLoader.ts
1. 修复前台选择了 Jina Reader 无法递归抓取网页
2. 新增 递归抓取到的 URL 也存储数据库
3. 递归抓页面支持选择 Page Parser
4. 支持自定义 深度（最大`3`）、自定义排除 URL
=> feat: add configurable parameters for webpage scraping

components/Chat.vue
=> fix: Optimize the line wrapping problem in Chinese chat

composables/markdown.ts, package.json, pnpm-lock.yaml
代码块的语言如果不支持高亮则默认使用 纯文本 模式，避免报错
=> fix: hljs fallback to plaintext if lang not support

composables/fetchWithAuth.ts
如果请求方法是 DELETE ，那么该方法会拿到错误的类型
目前没有好的方法，只能使用强制转换类型
=> fix:  $fetchWithAuth has the wrong type for the DELETE method

server/docstore/redis.ts, server/utils/recursiveUrlLoader.ts
#390 
LangChain的加载器 `RecursiveUrlLoader` 在基于URL递归加载时，会跳过不以 `/` 结尾的URL。
许多站点的目录级别的URL并不以 / 结尾。ChatOllama期望这类URL也被检索。
=> bugfix: recursive url loader should not skip on urls not trailing with slash

.env.example, components/ChatSettings.vue, components/settings/SettingsChatSettings.vue, nuxt.config.ts
可在 .env 文件中配置 `NUXT_PUBLIC_CHAT_MAX_ATTACHED_MESSAGES` 来修改最大附加消息的长度
=> feat: add env variable to set max attached messages  #361

server/utils/models.ts
#413 
Ollama 利用 num_predict 来限制生成的token数。目前限制为3000。目的是避免Ollama的模型无限输出。
=> set Ollama num_predict to 3000

.vscode/settings.json, components/ChatSessionList.vue, components/KnowledgeBaseForm.vue, components/Models.vue, components/ModelsSelectMenu.vue, composables/chat.ts, composables/useModels.ts, locales/en-US.json, locales/zh-CN.json, pages/knowledgebases/index.vue, utils/settings.ts
- 前端统一模型的处理，不再多次请求模型（数据缓存在 sessionStorage 中，且只有每次切换到 Models 页面才会重新获取最新的模型列表）
- 创建知识库中的模型下拉列表默认会从模型列表中提取 nomic-bert 家族的模型作为文本嵌入模型
#400
=> 统一模型的获取，增加 nomic-bert 提取

.env.example, nuxt.config.ts, server/api/models/chat/index.post.ts, server/rerank/cohere.ts
Use Peanut Shell API as the local reranking service, which is alternative to Cohere rerank API.
https://github.com/sugarforever/peanut-shell
=> feat: use Peanut Shell API as local reranking service

config/models.ts, docker-compose.yaml
1. OpenAI new model support - `gpt-4o`
2. Add docker compose service for `Peanut Shell` for local reranking
=> feat: gpt-4o support and peanut-shell integration

server/retriever/index.ts, server/utils/rag.ts
When Redis is not used, the documents are not split before getting added into vector store.
This PR is to enable documents split.
=> feat: documents split when redis not used

.gitignore, nuxt.config.ts, server/utils/mcp.ts
Remove the MCP servers settings from Nuxt runtime config.
Instead, we use a json config file `.mcp-servers.config`. It's loaded from current working directory by default. It can be overridden by environmental variable `MCP_SERVERS_CONFIG_PATH`.
=> feat: customized mcp servers config

components/ComponentPreview.vue
The previewed content should be vertically scrollable and not overflow.
=> fix: preview panel may overflow

composables/useOpenAIModels.ts
The OpenAI models are fetched via API, the models list should not be filtered.
=> fix: available openai models should not be filtered

components/settings/CustomServerForm.vue, locales/en-US.json, locales/zh-CN.json, server/api/models/index.get.ts
In the custom server form, users should provide the models endpoint if available.
Users don't have to manually enter models any more.
In the chat UI, the models from the customized service provider will be fetched in the run time.
=> feat: custom server form with models endpoint

layouts/default.vue
Moved the Charlie icon to the middle of the right edge.
=> fix: Charlie should not lay on top of the message send button

server/retriever/index.ts
Increase the chunk size of ingested documents. Nowadays, the main stream models already support much larger context window than 1 year ago.
=> feat: increase the chunk size to 3000 to fit nowadays much larger context window

server/api/models/index.get.ts, server/middleware/keys.ts
The construction of the models endpoint URL may cause the /v1/ section missing.
=> fix: custom models may not load correctly

components/settings/CustomServerForm.vue, server/api/models/index.get.ts
The custom service can't be saved with OpenAI type because of the scheme definition that requires at least 1 model available. But the models list is retrieved from OpenAI model list, not the custom service provider itself. In this case, when users haven't configured OpenAI API key, they won't have a valid OpenAI model list, then the custom service creation will fail on the models validation, and not be able to get saved.
Removed the constraint on it for now.
=> fix: the custom service is not saved
